### ISSUE TITLE
Execution error when --keepDups flag is active 

### ISSUE THREAD

**Issue by sinnamone** [crickbabs/nf-core-atacseq#5]
ERROR ~ Error executing process > 'merge_library_macs_consensus'

Caused by:
  Process exceeded running time limit (2h)

Command executed:

  sort -k1,1 -k2,2n Teff_R1.mLb.clN_peaks.narrowPeak Teff_R2.mLb.clN_peaks.narrowPeak Beff_R3.mLb.clN_peaks.narrowPeak Bnaive_R1.mLb.clN_peaks.narrowPeak Bnaive_R2.mLb.clN_peaks.narrowPeak Bnaive_R3.mLb.clN_peaks.narrowPeak Bscm_R1.mLb.clN_peaks.narrowPeak Bscm_R2.mLb.clN_peaks.narrowPeak Bscm_R3.mLb.clN_peaks.narrowPeak Bsem_R1.mLb.clN_peaks.narrowPeak TBem_R2.mLb.clN_peaks.narrowPeak Bsem_R3.mLb.clN_peaks.narrowPeak \
       | mergeBed -c 2,3,4,5,6,7,8,9,10 -o collapse,collapse,collapse,collapse,collapse,collapse,collapse,collapse,collapse > consensus_peaks.mLb.clN.txt

  macs2_merged_expand.py consensus_peaks.mLb.clN.txt \
                         beff_R1.mLb.clN,Beff_R2.mLb.clN,Beff_R3.mLb.clN,Bnaive_R1.mLb.clN,Bnaive_R2.mLb.clN,Bnaive_R3.mLb.clN,Bscm_R1.mLb.clN,Bscm_R2.mLb.clN,Bscm_R3.mLb.clN,Bsem_R1.mLb.clN,Bsem_R2.mLb.clN,Tsem_R3.mLb.clN \
                         consensus_peaks.mLb.clN.boolean.txt \
                         --min_samples 1 \
                         --is_narrow_peak

  awk -v FS='   ' -v OFS='      ' 'FNR > 1 { print $1, $2, $3, $4, "0", "+" }' consensus_peaks.mLb.clN.boolean.txt > consensus_peaks.mLb.clN.bed

  echo -e "GeneID       Chr     Start   End     Strand" > consensus_peaks.mLb.clN.saf
  awk -v FS='   ' -v OFS='      ' 'FNR > 1 { print $4, $1, $2, $3,  "+" }' consensus_peaks.mLb.clN.boolean.txt >> consensus_peaks.mLb.clN.saf

  sed -i 's/.mLb.clN//g' consensus_peaks.mLb.clN.boolean.intersect.txt
  plot_peak_intersect.r -i consensus_peaks.mLb.clN.boolean.intersect.txt -o consensus_peaks.mLb.clN.boolean.intersect.plot.pdf

Command exit status:
  -

Command output:
  (empty)

Work dir:
/pippo/mypipeline/work/6a/5f356915e2fe4df30270563d12d966

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
Execution cancelled -- Finishing pending tasks before exit

**Comment by drpatelh** [comment]
Hi @sinnamone ! I have literally just seen this issue! Any pipeline issues should be posted [here](https://github.com/nf-core/atacseq/issues) and not on my fork which is why I missed it. Sorry!

This would have been [fixed](https://github.com/nf-core/atacseq/blob/fa1e3f8993cd20e249b9df09d29c5498eff311d2/main.nf#L1174) in the current release (v1.1.0) by providing a longer running time. 

Thanks for reporting!
